version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      
      - run:
          name: "Yarn project and samples"
          command: |
            yarn
            cd samples/sample-datavault-react/
            yarn
            cd ../sample-datavault-solidity
            yarn
            cd ../..

      - run: 
          name: "Make sure you can print help and version"
          command: |
            ./dapploy -h
            ./dapploy -V

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # TODO run some more tests
      - store_test_results:
          path: reports


